SI_MPJ/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('autenticacion.urls')),
    url(r'^', include('administracion.urls')),
    url(r'^', include('control.urls')),
    url(r'^', include('donaciones.urls')),
    url(r'^admin/', admin.site.urls),
]

control/urls.py
"""
Nombre del Módulo: Archivo de URLs para la app “control”
Autores: Francisco Rivas, Kevin Rodríguez, Irving Oliva, Fernando Rivas
Última fecha de modificación: 04/10/2017
"""

from django.conf.urls import url
from . import views

urlpatterns = [
    # Inician URLs de Citas Medicas
    url(r'^agregar_cita/$', views.AgregarCita.as_view(), name='agregar_cita'),
    url(r'^agenda_citas/$', views.agenda_citas, name='agenda_citas'),
    url(r'^citamedica_confirmar/(?P<pk>\d+)$', views.EliminarCitaMedica.as_view(),name='EliminarCitaMedica'),
    url(r'^citamedica_actualizar/(?P<pk>\d+)$', views.ActualizarCitaMedica.as_view(), name='ActualizarCitaMedica'),
    url(r'^agregar_puntos_vitales/(?P<pk>\d+)$', views.PuntosVitales.as_view(), name='PuntosVitales'),
    url(r'^agregar_diagnostico/(?P<pk>\d+)$', views.Diagnostico.as_view(), name='Diagnostico'),
    url(r'^consultar_diagnostico/(?P<pk>\d+)$', views.ConsultarDiagnostico.as_view(), name='ConsultarDiagnostico'),
    # Finalizan URLs de Citas Medicas

    # Inician URLs de Medicamentos
    url(r'^agregar_medicamento/$', views.AgregarMedicamento.as_view(), name='agregar_medicamento'),
    url(r'^medicamentos/$', views.consultarMedicamento, name='consultarMedicamento'),
    url(r'^actualizar_medicamento/(?P<pk>\d+)$', views.ModificarMedicamento.as_view(),name='MedicamentoUpdate'),
    url(r'^desactivar_medicamento/(?P<medicamento_id>[0-9]+)$', views.desactivar_medicamento, name='desactivar_medicamento'),
    url(r'^confirmar_desactivar_medicamento/(?P<medicamento_id>[0-9]+)$', views.confirmar_desactivar_medicamento, name='confirmar_desactivar_medicamento'),
    # Finalizan URLs de Medicamentos

    # Inician URLs de Examenes
    url(r'^agregar_examen/$', views.AgregarExamen.as_view(), name='agregar_examen'),
    url(r'^examenes/$', views.consultarExamen, name='consultarExamen'),
    url(r'^actualizar_examen/(?P<pk>\d+)$', views.ModificarExamen.as_view(),name='ExamenUpdate'),
    url(r'^desactivar_examen/(?P<examen_id>[0-9]+)$', views.desactivar_examen, name='desactivar_examen'),
    url(r'^confirmar_desactivar_examen/(?P<examen_id>[0-9]+)$', views.confirmar_desactivar_examen, name='confirmar_desactivar_examen'),
    # Finalizan URLs de Examenes

    #Inician URLs de Lotes de Medicamentos
    url(r'^agregar_lotes/(?P<medicamento_id>[0-9]+)$', views.Agregar_lotes, name='agregar_lotes'),
    url(r'^lotes/(?P<medicamento_id>[0-9]+)$', views.consultarLotes, name='consultarLotes'),
    url(r'^actualizar_lote/(?P<lote_id>[0-9]+)$', views.LoteUpdate, name='actualizar_lote'),
    # Finalizan URLs de Lotes de Medicamentos

    # Inician URLs de Resultados de Examenes
    url(r'^agregar_resultado/(?P<exp_id>[0-9]+)$', views.AgregarResultado, name='agregar_resultado'),
    url(r'^consulta_lectura/(?P<exp_id>[0-9]+)$', views.consultarResultados, name='consultarResultados'),
    url(r'^detalle_resultado/(?P<pk>\d+)$', views.DetalleResultado.as_view(), name='Detalle_Resultado'),
    # Finalizan URLs de Resulados de Examenes

    # Inician URLs de Planes de Tratamientos
    url(r'^agregar_plan/(?P<expediente_id>\d+)$', views.PlanTratamientoCreate.as_view(), name='agregarPlan'),
    url(r'^detalle_plan/(?P<pk>\d+)/$', views.detallePlanes, name='detallePlan'),
    url(r'^imprimir_receta/(?P<pk>\d+)$', views.ImprimirRecetaPDFView.as_view(), name='imprimir_receta'),
    url(r'^agregar_receta/(?P<pt_id>\d+)$', views.RecetaCreateView.as_view(), name='agregarReceta'),
    url(r'^detalle_dosis/(?P<pk>\d+)$', views.detalleDosis, name='detalleDosis'),
    url(r'^agregar_dosis/(?P<r_id>\d+)$', views.DosisCreateView.as_view(), name='agregarDosis'),
    url(r'^actualizar_plan/(?P<pk>\d+)$', views.PlanTratamientoUpdateView.as_view(), name='actualizarPlan'),
    # Finalizan URLs de Planes de Tratamientos

    url(r'^agregar_diagnosticos/(?P<pk>\d+)$', views.Diagnostico2.as_view(), name='Diagnostico2'),
    url(r'^agregar_receta_diag/(?P<pt_id>\d+)$', views.AgregarRecetaDiagnostico, name='agregarRecetaDiagnostico2'),
]

control/models.py
# -*- coding: utf8 -*-
"""
Nombre del Módulo: Archivo de Modelos para la app “control”
Autores: Francisco Rivas, Kevin Rodríguez
Última fecha de modificación: 04/10/2017
"""

from django.db import models
from administracion.models import Expediente, Empleado
from django.core.validators import MinValueValidator
from django.shortcuts import reverse
from datetime import datetime
from django.utils.dateformat import DateFormat

# Create your models here.
CHOICES = (
    ('1', 'Disponible'),
    ('2', 'No Disponible'),
)
ESTADO_CHOICES = (
    ('1', 'En Tratamiento General'),
    ('2', 'En Tratamiento de Epilepsia'),
    ('2', 'Epilepsia Controlada'),
    ('4', 'Finalizado')
)
CITA_CHOICES = (
    ('1', 'Asignada'),
    ('2', 'En Consulta'),
    ('3', 'Finalizada'),
    ('4', 'Expirada'),
)
class PlanTratamiento(models.Model):
    fecha_inicio = models.DateField('Fecha de inicio', help_text = 'Formato: DD/MM/AAAA', blank = False, null = False)
    fecha_fin = models.DateField('Fecha de finalización', help_text = 'Formato: DD/MM/AAAA', blank = True, null = True)
    estado = models.CharField('estado', max_length = 1, choices = ESTADO_CHOICES, blank = False, null = False, default = ('1'))
    descripcion =  models.CharField('Descripción del Plan de Tratamiento', max_length = 1024, blank = True, null = True)

    expediente = models.ForeignKey(Expediente, blank = False, null = False)

    def __str__(self):
        # return self.expediente.num_expediente + " | Fecha de inicio del tratamiento: " + str(self.fecha_inicio)
        dformat = DateFormat(self.fecha_inicio)
        new_date = dformat.format('d/m/Y')
        return '{} - {} - {}: {}'.format(self.expediente.num_expediente, self.expediente.paciente, 'Inicio del tratamiento', str(new_date))

    def get_absolute_url(self):
        return reverse('detallePlan', args=[str(self.id)])

    def get_estado_display(self):
        for estado in ESTADO_CHOICES:
            if self.estado == estado[0]:
                return estado[1]

    class Meta:
        ordering = ["estado", "fecha_inicio"]
        verbose_name = 'Plan de Tratamiento'
        verbose_name_plural = 'Planes de Tratamiento'

class Receta(models.Model):
    fecha_prescripcion = models.DateTimeField('Fecha', blank = False, null = False, auto_now_add = True)
    indicaciones = models.CharField('Indicaciones', max_length = 1024, blank = False, null = False)
    plan_tratamiento = models.ForeignKey(PlanTratamiento, blank = False, null = False)

    def __str__(self):
        return '{} {}: {}'.format('Expediente', self.plan_tratamiento.expediente.num_expediente, self.indicaciones)

    def get_absolute_url(self):
        return reverse('detallePlan', args=[str(self.plan_tratamiento_id)])

    class Meta:
        ordering = ["fecha_prescripcion"]
        verbose_name = 'Receta'
        verbose_name_plural = 'Recetas'

class Medicamento(models.Model):
    nombre = models.CharField('Nombre del Medicamento', max_length = 64, blank = False, null = False, unique = True)
    stock = models.IntegerField('Existencias Totales', blank = False, null = False, default = 0, validators = [MinValueValidator(0)])
    estado = models.CharField('Estado', max_length = 1, choices = CHOICES, blank = False, null = False,default = ('1'))

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ["estado", "nombre"]
        verbose_name = 'Medicamento'
        verbose_name_plural = 'Medicamentos'


class Dosis(models.Model):
    cantidad=models.IntegerField('Cantidad', blank = False, null = False, validators = [MinValueValidator(0)])
    dosis=models.CharField('Dosis', max_length = 128, blank = False, null = False)
    medicamento = models.ForeignKey(Medicamento, blank = False, null = False)
    receta = models.ForeignKey(Receta, blank = False, null = False)

    def __str__(self):
        return "Medicamento: " + self.medicamento.nombre + ". Dosis: " + self.dosis

    class Meta:
        verbose_name = 'Dosis'
        verbose_name_plural = 'Dosis'

    def get_absolute_url(self):
        return reverse('detalleDosis', args=[str(self.receta_id)])



class LoteMedicamento(models.Model):
    fecha_ingreso = models.DateTimeField('Fecha de Ingreso', blank = False, null = False, auto_now_add = True)
    fecha_vencimiento = models.DateField('Fecha de Vencimiento', help_text = 'Formato: DD/MM/AAAA',blank = False, null = False)
    existencias = models.IntegerField('Existencias del Lote', blank = False, null = False, validators = [MinValueValidator(0)])
    medicamento = models.ForeignKey(Medicamento, blank = False, null = False)
    estado = models.CharField('estado', max_length=1, choices=CHOICES, blank=False, null=False, default=('1'))
    cantidad_ingreso = models.IntegerField('Cantidad que ingresó', blank = False, null = False, validators = [MinValueValidator(0)])

    def __str__(self):
        return "Lote de " + self.medicamento.nombre +". Vence: " + str(self.fecha_vencimiento)
    class Meta:
        ordering = ["medicamento", "fecha_ingreso"]
        verbose_name = 'Lote de Medicamento'
        verbose_name_plural = 'Lotes de Medicamentos'
    @classmethod
    def Lote_create(cls, fecha, exis, id):
        lote = cls(fecha_vencimiento=fecha, existencias=exis, medicamento=id)
        return lote

class Examen(models.Model):
    nombre = models.CharField('Nombre del Examen', max_length = 64, blank = False, null = False, unique = True)
    estado = models.CharField('estado', max_length = 1, choices = CHOICES, blank = False, null = False, default = ('1'))

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ["estado", "nombre"]
        verbose_name = 'Examen'
        verbose_name_plural = 'Exámenes'

class Resultado(models.Model): #Resultado de Examen de Laboratorio (Sólo para pacientes de la Fundación
    lectura = models.CharField('Lectura del Resultado', max_length = 1024, blank = False, null = False)
    fecha_realizacion = models.DateField('Fecha de Realización', help_text = 'Formato: DD/MM/AAAA', blank = False, null = False)
    fecha_lectura = models.DateField('Fecha de Lectura', help_text = 'Formato: DD/MM/AAAA', blank = False, null = False, auto_now_add = True)
    comentario = models.CharField('Comentario del Resultado', max_length = 1024, blank = True, null = True)
    expediente = models.ForeignKey(Expediente, blank = False, null = False)
    examen = models.ForeignKey(Examen, blank = False, null = False)

    def __str__(self):
        return "Lectura de " + self.examen.nombre + " en expediente: " + self.expediente.num_expediente


class CitaMedica(models.Model):
    fecha = models.DateField('Fecha', blank = False, null = False, help_text = 'Formato: DD/MM/AAAA')
    hora_inicio = models.TimeField('Hora de Inicio', blank = False, null = False)
    hora_fin = models.TimeField('Hora de Finalización', blank = False, null = False)
    peso = models.DecimalField('Peso', max_digits = 5, decimal_places = 2, blank = True, null = True, help_text = 'Peso (kg)', validators = [MinValueValidator(0)])
    talla = models.DecimalField('Talla', max_digits = 5, decimal_places = 2, blank = True, null = True, help_text = 'Talla (m)', validators = [MinValueValidator(0)])
    imc = models.DecimalField('IMC', max_digits = 5, decimal_places = 1, blank = True, null = True, help_text = 'Índice de Masa Corporal (kg/m2)', validators = [MinValueValidator(0)])
    temp = models.DecimalField('C°', max_digits = 5, decimal_places = 2, blank = True, null = True, help_text = 'Temperatura (°C)')
    fc = models.IntegerField('FC', blank = True, null = True, help_text = 'Frecuencia Cardíaca (lat/min)', validators = [MinValueValidator(0)])
    fr = models.IntegerField('FR', blank = True, null = True, help_text = 'Frecuencia Respiratoria (resp/min)', validators = [MinValueValidator(0)])
    pa = models.CharField('PA', max_length = 6, blank = True, null = True, help_text = 'Presión Arterial ###/##')
    cx = models.CharField('Cx', max_length = 63, blank = True, null = True, help_text = 'Consulta por:')
    pe = models.TextField('P.E.', max_length = 1024, blank = True, null = True, help_text = 'Presenta Enfermedad')
    ef = models.TextField('Examen Físico', max_length = 1024, blank = True, null = True)
    antecedente = models.TextField('Antecedente', max_length = 1024, blank = True, null = True)
    dx = models.CharField('Dx', max_length = 63, blank = True, null = True, help_text = 'Diagnóstico')
    plan = models.CharField('Plan', max_length = 1024, blank = True, null = True)
    estado = models.CharField('Estado de la Cita', max_length = 1, choices = CITA_CHOICES, blank = False, null = False, default = ('1'))
    precio_consulta = models.DecimalField('Precio de la Consulta', max_digits = 8, decimal_places = 2, blank = True, null = True, validators = [MinValueValidator(0)])
    precio_examen = models.DecimalField('Precio del Examen', max_digits = 8, decimal_places = 2, blank = True, null = True, validators = [MinValueValidator(0)])
    fecha_proxima = models.DateField('Fecha de Próxima Cita', blank=False, null=True, help_text='Formato: DD/MM/AAAA')
    medico = models.ForeignKey(Empleado, blank = False, null = False)
    plan_tratamiento = models.ForeignKey(PlanTratamiento, blank = True, null = True)
    examen = models.ForeignKey(Examen, blank = True, null = True)
    convenio = models.BooleanField('¿Convenio?', default=False)

    def __str__(self):
        return "Cita Médica por médico: " + self.medico.nombre + ", fecha: " + str(self.fecha)

    def get_edad(self):
        diff = (self.fecha - self.plan_tratamiento.expediente.paciente.fecha_nacimiento).days
        edad = str(int(diff / 365)) # Edad en años
        string = ' años'
        if edad == '0':
            edad = str(int(diff / 12))# Edad en meses
            string = ' meses'
        return edad + string

    class Meta:
        ordering=["fecha", "hora_inicio"]
        verbose_name = 'Cita Médica'

control/templates/control/actualizar_lotes.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main id="movermain">
        <div><b style="font-size: 22px;">Actualizar Lote</b></div>

        <form class="col s12" method="post">
            {% csrf_token %}

            <div class="input-field col s6 fecha_vencimiento">

                <input id ="fecha_vencimiento" type="text" name="fecha_vencimiento" value="{{ fecha_vencimiento|date:"d/m/Y"}}"  >


            </div>

            <div class="input-field col s6">
                <input id="existencias" type="number"  name="existencias" value="{{ existencias }}" min="0" >
                <label for="exitencias">Existencias:</label>
            </div>

            <button class="btn btn-primary"  type="submit" name="action" href="/actualizar_lote/{{lote_id}}">Aceptar
                <i class="material-icons right">send</i>
            </button>
            <a class="btn btn-danger" href="/lotes/{{ medicamento }}" type="submit">Cancelar <i class="material-icons right">cancel</i></a>

        </form>

       <script type="text/javascript">
            $('input[name="fecha_vencimiento"]').mask('00/00/0000');
        </script>
        <script type="text/javascript">
            $('input[name="fecha_vencimiento"]').dblclick(function() {
                $('input[name="fecha_vencimiento"]').datepicker('show');
            });
            $('input[name="fecha_vencimiento"]').click(function() {
                $('input[name="fecha_vencimiento"]').datepicker('hide');
            });
        </script>
        <script type="text/javascript">
            $('input[name="fecha_vencimiento"]').datepicker({
                format: "dd/mm/yyyy",
                todayBtn: "linked",
                maxViewMode: 3,
                autoclose: true,
                language: "es",
                daysOfWeekHighlighted: "0",
                clearBtn: true,
                todayHighlight: true,
                orientation: "bottom auto",
                container: "div.fecha_vencimiento"
            });
        </script>



        <script type="text/javascript">
            (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
        </script>
    </main>

{%endblock%}

control/templates/control/agregar_dosis.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %}
{% block content %}
    <main id="movermain">
        <form action="" method="POST" class="viewform">
            {% csrf_token %}
            {% form form=form %}
                {% part form.cantidad prefix %}<i class="material-icons prefix">local_drink</i>{% endpart %}
                {% part form.dosis prefix %}<i class="material-icons prefix">colorize</i>{% endpart %}
                {% part form.medicamento prefix %}<i class="material-icons prefix">healing</i>{% endpart %}
            {% endform %}
            <button class="btn btn-primary"  type="submit" name="action" >Agregar Dosis
                <i class="material-icons right">send</i>
            </button>
            <a class="btn btn-danger" href="{% url 'detalleDosis' pk=view.kwargs.r_id %}">Cancelar<i class="material-icons right">cancel</i></a>
        </form>
        {% if messages %}
            {% for mensaje in messages %}
                <script type="text/javascript">
                    (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
                </script>
            {% endfor %}
        {% endif %}
    </main>
{% endblock %}

control/templates/control/agregar_lotes.html
{% extends 'base.html' %}
{% load static %}
{% include 'material/includes/material_css.html' %}
<script src="{% static 'material/js/jquery.js' %}"></script>
{% include 'material/includes/material_js.html' %}
{% load material_form %}

{% block content %}
    <main id="movermain">
        <form action="" method="POST" class="viewform">
            {% csrf_token %}

            {% form form=lote_form %}
                {% part form.fecha_vencimiento prefix %} <i class="material-icons prefix">date_range</i>{% endpart %}
                {% attr form.fecha_vencimiento 'group' class append %}fecha_1{% endattr %}
                {% attr form.fecha_vencimiento 'widget' autocomplete  append %}off{% endattr %}
                {% part form.existencias prefix %}<i class="material-icons prefix">poll</i>{% endpart %}
            {% endform %}

            <button class="btn btn-primary"  type="submit" name="action" >Registrar
                <i class="material-icons right">send</i>
            </button>
            <a class="btn btn-danger" href="/medicamentos" type="submit">Regresar<i class="material-icons right">cancel</i></a>

        </form>

        <script type="text/javascript">
            $('input[name="lote-fecha_vencimiento"]').mask('00/00/0000');
        </script>

        <script type="text/javascript">
            $('input[name="lote-fecha_vencimiento"]').dblclick(function() {
                $('input[name="lote-fecha_vencimiento"]').datepicker('show');
            });
            $('input[name="lote-fecha_vencimiento"]').click(function() {
                $('input[name="lote-fecha_vencimiento"]').datepicker('hide');
            });
        </script>
        <script type="text/javascript">
            $('input[name="lote-fecha_vencimiento"]').datepicker({
                format: "dd/mm/yyyy",
                todayBtn: "linked",
                maxViewMode: 3,
                autoclose: true,
                language: "es",
                daysOfWeekHighlighted: "0",
                clearBtn: true,
                todayHighlight: true,
                orientation: "bottom auto",
                container: "div.fecha_1"
            });
        </script>

        <script type="text/javascript">
            (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
        </script>

    </main>
{% endblock %}>

control/templates/control/agregar_receta.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %}
{% block content %}
    <main id="movermain">
        <form action="" method="POST" class="viewform">
            {% csrf_token %}
            {% form form=form %}
                {% part form.indicaciones prefix %}<i class="material-icons prefix">content_paste</i>{% endpart %}
            {% endform %}
            <button class="btn btn-primary"  type="submit" name="action" >Agregar Receta
                <i class="material-icons right">send</i>
            </button>
        {% if  not diag %}
            <a class="btn btn-danger" href="{% url 'detallePlan' pk=view.kwargs.pt_id %}">Cancelar<i class="material-icons right">cancel</i></a>
        {% else %}
        <a class="btn btn-danger" href="{% url 'agenda_citas'%}">Finalizar Diagnostico<i class="material-icons right">cancel</i></a>
        {% endif %}
        </form>
        {% if messages %}
            {% for mensaje in messages %}
                <script type="text/javascript">
                    (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
                </script>
            {% endfor %}
        {% endif %}
    </main>
{% endblock %}

control/templates/control/agregar_resultado.html
{% extends 'base.html' %}
{% load static %}
{% include 'material/includes/material_css.html' %}
<script src="{% static 'material/js/jquery.js' %}"></script>
{% include 'material/includes/material_js.html' %}
{% load material_form %}

{% block content %}
    <main id="movermain">
        <form action="" method="POST" class="viewform">
            {% csrf_token %}

            {% form form=resultado_form %}
                {% part form.examen prefix %} <i class="material-icons prefix">assignment</i>{% endpart %}
                {% part form.fecha_realizacion prefix %} <i class="material-icons prefix">date_range</i>{% endpart %}
                {% attr form.fecha_realizacion 'group' class append %}fecha_1{% endattr %}
                {% attr form.fecha_realizacion 'widget' autocomplete  append %}off{% endattr %}
                {% part form.lectura prefix %}<i class="material-icons prefix">poll</i>{% endpart %}
                {% part form.comentario prefix %}<i class="material-icons prefix">poll</i>{% endpart %}
            {% endform %}

            <button class="btn btn-primary"  type="submit" name="action" >Registrar
                <i class="material-icons right">send</i>
            </button>
            <a class="btn btn-danger" href="{% url 'expediente' pk=pk %}" type="submit">Cancelar<i class="material-icons right">cancel</i></a>

        </form>

        <script type="text/javascript">
            $('input[name="resultado-fecha_realizacion"]').mask('00/00/0000');
        </script>


        <script type="text/javascript">
            (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
        </script>

        <script type="text/javascript">
            $('input[name="resultado-fecha_realizacion"]').dblclick(function() {
                $('input[name="resultado-fecha_realizacion"]').datepicker('show');
            });
            $('input[name="resultado-fecha_realizacion"]').click(function() {
                $('input[name="resultado-fecha_realizacion"]').datepicker('hide');
            });
        </script>

        <script type="text/javascript">
            $('input[name="resultado-fecha_realizacion"]').datepicker({
                format: "dd/mm/yyyy",
                todayBtn: "linked",
                maxViewMode: 3,
                autoclose: true,
                language: "es",
                daysOfWeekHighlighted: "0",
                clearBtn: true,
                todayHighlight: true,
                orientation: "bottom auto",
                container: "div.fecha_1"
            });
        </script>

        <script type="text/javascript">
            $(function(){
                // turn the element to select2 select style
                $('.select-search').select2();
            });
        </script>

    </main>
{% endblock %}>

control/templates/control/citamedica_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main id="movermain">
        <form action="" method="post">{% csrf_token %}
            <p>¿Está seguro que desea eliminar la cita: "{{ object }}"?</p>

            <button class="btn btn-danger">Aceptar
                <i class="material-icons right">warning</i>
            </button>

            <a class="btn btn-primary" href={% url 'agenda_citas' %}>Cancelar
                <i class="material-icons right">cancel</i></a>
        </form>
    </main>
{% endblock %}

control/templates/control/consultaExamenes.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main id="movermain" class="consulta-tabla">
        <header>
            <div class="nav-wrapper">

            </div>
        </header>
        <table class="table table-striped table-bordered table-hover" data-toggle="bootgrid" id = "moverTabla">
            <thead>
            <tr>
                <th> Fecha Realizacion</th>
                <th>Fecha Lectura</th>
                <th>Tipo de Examen</th>
                {% if perms.control.change_resultado%}
                    <th>Vizualizar</th>
                {% endif %}
            </tr>
            </thead>

            <tbody>
            {% for resultados in resultados_lis %}
                <tr>
                    <td>{{resultados.fecha_lectura}}</td>
                    <td>{{resultados.fecha_realizacion}}</td>
                    <td>{{resultados.examen}}</td>

                    {% if perms.control.change_lotemedicamento%}
                        <td>
                            <a class="btn btn-primary" href="/detalle_resultado/{{resultados.id}}"><i class="material-icons">visibility</i></a>
                        </td>
                    {% endif %}
                </tr>

            {% endfor %}
            </tbody>
        </table>
        {% if messages %}
            {% for mensaje in messages %}
                <script type="text/javascript">
                    (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
                </script>
            {% endfor %}
        {% endif %}
    </main>

{%endblock%}

control/templates/control/consultaLotes.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main id="movermain" class="consulta-tabla">
        <header>
            <div class="nav-wrapper">

            </div>
        </header>
        <table class="table table-striped table-bordered table-hover" data-toggle="bootgrid" id = "moverTabla">
            <thead>
            <tr>
                <th>Fecha de Ingreso</th>
                <th>Fecha de Vencimiento</th>
                <th>Medicamento</th>
                <th>Existencia</th>


                {% if perms.control.change_lotemedicamento%}
                    <th>Modificar</th>
                {% endif %}
            </tr>
            </thead>

            <tbody>
            {% for lotes in lotes_list %}
                <tr>
                    <td>{{lotes.fecha_ingreso}}</td>
                    <td>{{lotes.fecha_vencimiento}}</td>
                    <td>{{lotes.medicamento|title}}</td>
                    <td>{{lotes.existencias}}</td>

                    {% if perms.control.change_lotemedicamento%}
                        <td>
                            <a class="btn btn-primary" href="/actualizar_lote/{{lotes.id}}"><i class="material-icons">edit</i></a>
                        </td>
                    {% endif %}
                </tr>

            {% endfor %}
            </tbody>
        </table>
        <br>
        <a class="btn btn-primary" href="javascript:history.back()" >Regresar
            <i class="material-icons right">reply</i></a>
        {% if messages %}
            {% for mensaje in messages %}
                <script type="text/javascript">
                    (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
                </script>
            {% endfor %}
        {% endif %}
    </main>

{%endblock%}