SI_MPJ/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('autenticacion.urls')),
    url(r'^', include('administracion.urls')),
    url(r'^', include('control.urls')),
    url(r'^', include('donaciones.urls')),
    url(r'^admin/', admin.site.urls),
]

donaciones/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^agregar_donacion/$', views.registroDonacion.as_view(), name='agregar_donacion'),
    url(r'^donaciones/$', views.consultarDonaciones, name='consultarDonaciones'),
    url(r'^donaciones/(?P<pk>\d+)$', views.DetalleDonacion.as_view(), name='detalle_donacion'),
    url(r'^donar_bienmueble/$', views.donar_mueble, name='donar_bienmueble'),
    url(r'^actualizar_donacion/(?P<id>[0-9]+)$', views.ModificarDonacionDinero, name='actualizar_donacion'),
    #inician URLS de Donadores
    url(r'^agregar_donadores/$', views.donadoresRegistar, name='agregar_donadores'),
    url(r'^actualizar_donadores/(?P<id>[0-9]+)$', views.actualizarDonador, name='actualizar_donador'),
    url(r'^desactivar_donador/(?P<donador_id>[0-9]+)$', views.desactivar_donador, name='desactivar_donador'),
    url(r'^confirmar_desactivar/(?P<donador_id>[0-9]+)$', views.confirmar_desactivar_donador, name='confirmar'),
    url(r'^donadores/$', views.consultarDonadores, name='Consultar_donaciones'),
    
    # Inician URLs de BienMuebles
    url(r'^agregar_bien_mueble/$', views.AgregarBienMueble.as_view(), name='agregar_bien_mueble'),
    url(r'^bien_muebles/$', views.consultarBienMueble, name='consultarBienMueble'),
    url(r'^actualizar_bien_mueble/(?P<pk>\d+)$', views.ModificarBienMueble.as_view(),name='BienMuebleUpdate'),
    url(r'^desactivar_bien_mueble/(?P<bien_mueble_id>[0-9]+)$', views.desactivar_bien_mueble, name='desactivar_bien_mueble'),
    url(r'^confirmar_desactivar_bien_mueble/(?P<bien_mueble_id>[0-9]+)$', views.confirmar_desactivar_bien_mueble, name='confirmar_desactivar_bien_mueble'),
    # Finalizan URLs de BienMuebles

    # Inician URLs de Lotes de Bien Mueble
    url(r'^agregar_lote_mueble/(?P<bien_mueble_id>[0-9]+)$', views.Agregar_lote_muebles, name='agregar_lote_mueble'),
    url(r'^lotes_bienes_muebles/(?P<bien_mueble_id>[0-9]+)$', views.consultarLoteMuebles, name='consultarLoteMuebles'),
    url(r'^actualizar_lote_mueble/(?P<lote_mueble_id>[0-9]+)$', views.LoteMuebleUpdate, name='actualizar_lote_mueble'),
    # Finalizan URLs de Lotes de Bien Mueble

    #Inician URLS de Salidas
    url(r'^donar_medicamento/$', views.Donar_lote, name='donar_lotemedicamento'),
    url(r'^donaciones_lote/(?P<pk>\d+)$', views.DetalleLoteDonacion.as_view(), name='detalle_lotes'),
    url(r'^salida_efectivo/$', views.SalidaEfectivo, name='salida_efectivo'),
    url(r'^salida_bienmueble/$', views.SalidaBienMueble, name='salida_bienmueble'),
    url(r'^salida_medicamentos/$', views.salida_medicamentos, name='salida_medicamentos'),
    #Finalizan URLS de Salidas

    url(r'^agregar_procedimiento/$', views.AgregarIngresoProcedimiento.as_view(), name='agregar_procedimiento'),
    url(r'^actualizar_procedimiento/(?P<pk>\d+)$', views.ModificarIngresoProcedimiento.as_view(), name='ProcedimientoUpdate'),
    url(r'^procedimientos/$', views.consultarProcedimientos, name='consultarProcedimientos'),
    url(r'^procedimientos_paciente/(?P<pac_id>[0-9]+)$', views.consultarProcedimientosPaciente, name='procedimientos_paciente'),

]

donaciones/models.py
"""# -*- coding: utf8 -*-"""
from django.db import models
from django.core.validators import MinValueValidator
from administracion.models import Paciente
from control.models import CHOICES, LoteMedicamento, Medicamento
from datetime import date

# Create your models here.

BANCOS = (('1', 'Banco Agricola'),('2', 'Banco Scotiabank'))

class Institucion(models.Model):
    nombre_institucion= models.CharField('Nombre de la Institución', max_length = 128)
    direccion= models.CharField('Dirección de la Institución', max_length=256, blank=False,null=False)
    nit_institucion = models.CharField('Número de NIT', max_length=17, blank=True, null=False, help_text='Formato: XXXX-XXXXXX-XXX-X', unique=True)
    telefono_institucion = models.CharField('Número de teléfono', max_length=9, help_text='Formato: XXXX-XXXX', blank=True, null=True, unique=True)

    def __str__(self):
        return self.nombre_institucion

    class Meta:
        ordering = ['nombre_institucion']
        verbose_name = 'Institucion'
        verbose_name_plural = 'Instituciones'

class Donador(models.Model):
    nombre = models.CharField('Nombres del donador', max_length=40, blank=False, null=False)
    apellido = models.CharField('Apellidos del donador', max_length=40, blank=False, null=False)
    telefono = models.CharField('Número de teléfono', max_length=9, help_text='Formato: XXXX-XXXX', blank=False, null=False, unique=True)
    email = models.EmailField('Correo Electrónico', max_length=254, blank=True, null=True, unique=True)
    nit = models.CharField('Número de NIT', max_length=17, blank=False, null=False, help_text='Formato: XXXX-XXXXXX-XXX-X', unique=True)
    institucion = models.OneToOneField(Institucion, help_text='Institución a la que pertenece el Donador', blank=True, null=True)
    activo = models.BooleanField('¿Activo?', default=True)
    def __str__(self):
        return '{} {}'.format(self.nombre, self.apellido)

    class Meta:
        ordering = ['apellido']
        verbose_name = 'Donador'
        verbose_name_plural = 'Donadores'

class BienMueble(models.Model):
    nombre = models.CharField('Nombre del Bien Mueble', max_length=40, blank=False, null=False, unique = True)
    stock = models.IntegerField('Existencias Totales', blank = False, null = False, default = 0, validators = [MinValueValidator(0)])
    estado  = models.CharField('Estado', max_length = 1, choices = CHOICES, blank = False, null = False,default = ('1'))


    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ['nombre']
        verbose_name = 'Bien Mueble'
        verbose_name_plural = 'Bienes Muebles'

class LoteBienMueble(models.Model):
    fecha_ingreso = models.DateTimeField('Fecha de Ingreso', blank=False, null=False, auto_now_add=True)
    cantidad_ingreso = models.IntegerField('Cantidad o Monto inicial', blank=False, null=False, validators=[MinValueValidator(0)])
    existencias = models.IntegerField('Existencias del Lote', blank=False, null=False, validators=[MinValueValidator(0)])
    bien_mueble = models.ForeignKey(BienMueble, blank=False, null=False)
    estado = models.CharField('estado', max_length=1, choices=CHOICES, blank=False, null=False, default=('1'))

    def __str__(self):
        return "Lote de " + self.bien_mueble.nombre

    class Meta:
        ordering = ["bien_mueble", "fecha_ingreso"]
        verbose_name = 'Lote de Bien Mueble'
        verbose_name_plural = 'Lotes de Bien Mueble'

class Donacion(models.Model):
    fecha_ingreso  = models.DateField('Fecha de Ingreso', blank=False, null=False, default=date.today)
    cantidad = models.IntegerField(help_text = 'Cantidad o Monto Donado', blank=False, null=False, validators=[MinValueValidator(0)])
    monto_inicial = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    descripcion = models.CharField(help_text = 'Descripción de la Donación', max_length=512, blank=False, null=False)
    donador = models.ForeignKey(Donador, blank=False, null=False)
    fecha_remesa = models.DateField('Fecha de Remesa', help_text='Formato: DD/MM/AAAA', blank=True, null=True)
    lote_medicamento = models.OneToOneField(LoteMedicamento, blank=True, null=True)
    lote_bienmueble = models.OneToOneField(LoteBienMueble, blank=True, null=True)
    banco = models.CharField(max_length=1, choices=BANCOS, blank=True, null=True)
    comprobante = models.BooleanField('¿Solicitar Comprobante?', default=False)

    def __str__(self):
        return "Donación de " + self.donador.nombre

    class Meta:
        ordering = ["donador"]
        verbose_name = 'Donación'
        verbose_name_plural = 'Donaciones'

class Salida(models.Model):
    fecha = models.DateField('Fecha de Salida')
    ingreso_medicamento = models.DecimalField('Ingreso por medicamentos ($)', max_digits = 8, decimal_places = 2, blank = True, null = True, validators = [MinValueValidator(0)])
    concepto = models.CharField('En concepto de', max_length=1024, blank=False, null=True)
    paciente = models.ForeignKey(Paciente, null=True, blank=True, help_text='Paciente')
    donacion = models.ManyToManyField(Donacion, blank=True, help_text='Donacion')

    def __str__(self):
        return '{}: {}'.format(self.fecha, self.concepto)

    class Meta:
        verbose_name = 'Salida'
        verbose_name_plural = 'Salidas'

class DetalleSalida(models.Model):
    cantidad = models.IntegerField(help_text='Cantidad a donar', blank=False, null=False, validators=[MinValueValidator(0)])
    salida = models.ForeignKey(Salida, null=False, blank=False)
    medicamento = models.ForeignKey(Medicamento, null=True, blank=True, help_text='Medicamento')
    bienmueble = models.ForeignKey(BienMueble, null=True, blank=True, help_text='Bien Mueble')

    class Meta:
        verbose_name = 'Detalle de Salida'
        verbose_name_plural = 'Detalles de Salida'

class Procedimiento(models.Model):
    fecha  = models.DateField('Fecha de Ingreso', blank=False, null=False, default=date.today)
    monto = models.IntegerField(validators=[MinValueValidator(0)], null=False, blank=False)
    descripcion = models.CharField(help_text = 'Concepto del Procedimiento', max_length=512, blank=False, null=False)
    paciente = models.ForeignKey(Paciente, blank=False, null=False)

    def __str__(self):
        return "Donación en concepto de " + self.descripcion

donaciones/forms.py
"""
Nombre del Módulo: Archivo de formularios para la app “donaciones”
Autores: Kevin Rodríguez, Irving Oliva, Fernando Rivas
Última fecha de modificación: 04/11/2017
"""
from django import forms
from django.contrib.auth.models import User
from material import *
from .models import *

# Inician Formularios de Donador
class DonadorForm(forms.ModelForm):
    class Meta:
        model=Donador
        fields=['nombre','apellido','telefono','email','nit']

    layout = Layout(Fieldset('Información del Donador:',
                             Row('nombre', 'apellido'), Row('telefono', 'email', 'nit')))

class InstitucionForm(forms.ModelForm):
    class Meta:
        model = Institucion
        fields = ['nombre_institucion', 'direccion', 'telefono_institucion', 'nit_institucion']

    layout = Layout(Fieldset('Información de Institucion:',
                             Row('nombre_institucion', 'telefono_institucion'),
                             Row('direccion', 'nit_institucion')))

# Finalizan Formularios de Donadors

# Inician Formularios de Donaciones
class DonacionForm(forms.ModelForm):
    class Meta:
        model = Donacion
        fields = ['fecha_ingreso', 'cantidad', 'descripcion', 'donador', 'lote_bienmueble','lote_medicamento']
    layout = Layout(Fieldset('Información de la Donación:'), Row('donador'),Row('lote_bienmueble', 'fecha_ingreso'), Row('cantidad', 'descripcion'))

    def __init__(self, *args, **kwargs):
        super(DonacionForm, self).__init__(*args, **kwargs)
        self.fields['donador'].widget.attrs['readonly'] = True
        self.fields['cantidad'].widget.attrs['readonly'] = True
        self.fields['descripcion'].widget.attrs['readonly'] = True
        self.fields['fecha_ingreso'].widget.attrs['readonly'] = True
        self.fields['lote_bienmueble'].widget.attrs['readonly'] = True


class NombreDonadorForm(forms.ModelForm):
    class Meta:
        model = Donacion
        fields = ['donador']
    layout = Layout(Fieldset('Información del Donador:'),Row('donador'))

    def __init__(self, *args, **kwargs):
        super(NombreDonadorForm, self).__init__(*args, **kwargs)
        self.fields['donador'].widget.attrs['readonly'] = True


class DonacionDineroForm(forms.ModelForm):
    class Meta:
        model = Donacion
        fields = ['fecha_ingreso', 'cantidad', 'descripcion','fecha_remesa', 'banco']
    layout = Layout(Fieldset('Información de la Donación:'), Row('cantidad', 'fecha_ingreso'), Row('descripcion'), Row('fecha_remesa', 'banco'))

    def __init__(self, *args, **kwargs):
        super(DonacionDineroForm, self).__init__(*args, **kwargs)
        self.fields['cantidad'].widget.attrs['readonly'] = True
        self.fields['descripcion'].widget.attrs['readonly'] = True
        self.fields['fecha_ingreso'].widget.attrs['readonly'] = True

class DonacionDineroForm2(forms.ModelForm):
    class Meta:
        model = Donacion
        fields = ['fecha_ingreso', 'cantidad', 'descripcion','fecha_remesa', 'banco']
    layout = Layout(Fieldset('Información de la Donación:'), Row('cantidad', 'fecha_ingreso'), Row('descripcion'), Row('fecha_remesa', 'banco'))

    def __init__(self, *args, **kwargs):
        super(DonacionDineroForm2, self).__init__(*args, **kwargs)
        self.fields['cantidad'].widget.attrs['readonly'] = True
        self.fields['descripcion'].widget.attrs['readonly'] = True
        self.fields['fecha_ingreso'].widget.attrs['readonly'] = True
        self.fields['fecha_remesa'].widget.attrs['readonly'] = True
        self.fields['banco'].widget.attrs['readonly'] = True

class DonacionModForm(forms.ModelForm):
    class Meta:
        model = Donacion
        fields = ['fecha_ingreso', 'cantidad', 'descripcion', 'donador', 'comprobante']

    layout = Layout(Fieldset('Información de la Donación:'), Row('donador', 'fecha_ingreso'),
                    Row('cantidad', 'descripcion'), Row('comprobante'))

    def __init__(self, *args, **kwargs):
        super(DonacionModForm, self).__init__(*args, **kwargs)
        self.fields['donador'].widget.attrs['readonly'] = True
        self.fields['fecha_ingreso'].widget.attrs['readonly'] = True

# Finalizan Formularios de Donaciones

# Inician Formularios para lotes de Bienes Muebles
class LoteForm(forms.ModelForm):


    class Meta:
        model=LoteBienMueble
        fields=['existencias']

        Layout = Layout(Fieldset(' Agregar Lote Bien Mueble:', Row('existencias')))

class BienMuebleForm(forms.ModelForm):
    class Meta:
        model = LoteBienMueble
        fields = ['bien_mueble']

    layout = Layout(Fieldset('Información del Bien Mueble:'), Row('bien_mueble'))

    def __init__(self, *args, **kwargs):
        super(BienMuebleForm, self).__init__(*args, **kwargs)
        self.fields['bien_mueble'].widget.attrs['readonly'] = True

# Finalizan Formularios para lotes de Bienes Muebles


# Inician Formularios para lotes de Medicamentos para Donaciones
class LoteMediForm(forms.ModelForm):
    class Meta:
        model = LoteMedicamento
        fields = ['medicamento','fecha_vencimiento']

    layout = Layout(Fieldset('Información del Lote De Medicamentos:'), Row('medicamento'),'fecha_vencimiento')

    def __init__(self, *args, **kwargs):
        super(LoteMediForm, self).__init__(*args, **kwargs)
        self.fields['medicamento'].widget.attrs['readonly'] = True


class DetalleLote(forms.ModelForm):
    class Meta:
        model = Donacion
        fields = ['fecha_ingreso', 'cantidad', 'descripcion', 'donador','lote_medicamento']
    layout = Layout(Fieldset('Información de la Donación:'), Row('donador'),Row('lote_medicamento', 'fecha_ingreso'), Row('cantidad', 'descripcion'))

    def __init__(self, *args, **kwargs):
        super(DetalleLote, self).__init__(*args, **kwargs)
        self.fields['donador'].widget.attrs['readonly'] = True
        self.fields['cantidad'].widget.attrs['readonly'] = True
        self.fields['descripcion'].widget.attrs['readonly'] = True
        self.fields['fecha_ingreso'].widget.attrs['readonly'] = True
        self.fields['lote_medicamento'].widget.attrs['readonly'] = True

# Finalizan Formularios para lotes de Medicamentos para Donaciones

# Inician los Formularios de Salida de Efectivo
class SalidaFrom(forms.ModelForm):
    class Meta:
        model = Salida
        fields = ['concepto']

    layout = Layout(Fieldset(' Concepto de la Salida:'), Row('concepto'))

class DetalleForm(forms.ModelForm):
    class Meta:
        model = DetalleSalida
        fields = ['cantidad']

    layout = Layout(Fieldset(' Cantidad de salida:'), Row('cantidad'))

# Finalizan los Formularios de Salida de Efectivo

# Inician los Formularios de Salida de Bien Mueble

class SalidaBienMuebleForm(forms.ModelForm):
        class Meta:
            model = LoteBienMueble
            fields = ['bien_mueble', ]

        layout = Layout(Fieldset('Informacion del Bien Mueble:'), Row('bien_mueble'))

        def __init__(self, *args, **kwargs):
            super(SalidaBienMuebleForm, self).__init__(*args, **kwargs)
            self.fields['bien_mueble'].widget.attrs['readonly'] = True

# Finalizan los Formularios de Salida de Bien Mueble

donaciones/templates/donaciones/Detalle_lote.html
{% extends 'base.html' %}
{% load static %}
{% include 'material/includes/material_css.html' %}
<script src="{% static 'material/js/jquery.js' %}"></script>
{% include 'material/includes/material_js.html' %}
{% load material_form %}

{% block content %}
    <main id="movermain">
        <form action="" method="post">{% csrf_token %}



                {% form form=form %}
                    {% part form.donador prefix %}<i class="material-icons prefix">account_box</i>{% endpart %}
                    {% attr form.donador 'widget' disabled%}
                        disabled
                    {% endattr %}

                    {% part form.lote_medicamento prefix %}<i class="material-icons prefix">event_seat</i>{% endpart %}
                    {% attr form.lote_medicamento 'widget' disabled%}
                        disabled
                    {% endattr %}

                    {% part form.fecha_ingreso prefix %}<i class="material-icons prefix">date_range</i>{% endpart %}
                    {% part form.cantidad prefix %}<i class="material-icons prefix">shopping_basket</i>{% endpart %}
                    {% part form.descripcion prefix %}<i class="material-icons prefix">reorder</i>{% endpart %}
                {% endform %}



            <a class="btn btn-primary"  href={% url 'consultarDonaciones'  %}>Regresar
                <i class="material-icons right">reply</i>
            </a>

        </form>


    </main>
{% endblock %}

donaciones/templates/donaciones/consultaDonaciones.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
    <main id="movermain" class="consulta-tabla">
        <header>

        </header>
        <table class="table table-striped table-bordered table-hover" data-toggle="bootgrid" id = "moverTabla">
            <thead>
            <tr>
                <th>Fecha de Donación</th>
                <th>Donador</th>
                <th>Tipo</th>
                <th>Monto/Cantidad</th>
                <th>Estado</th>
                <th>Comprobante</th>
                {% if perms.donaciones.change_donacion%}
                    <th>Detallar</th>
                {% endif %}
            </tr>
            </thead>

            <tbody>
            {% for donaciones in donaciones_list %}
                <tr>
                    <td>{{donaciones.fecha_ingreso}}</td>
                    <td>{{donaciones.donador}}</td>
                    <td style="text-align: left;">{% if donaciones.lote_bienmueble %}
                        {% if perms.donaciones.change_lotebienmueble %}
                            <i class="material-icons">event_seat</i> <a href="{% url 'consultarLoteMuebles' donaciones.lote_bienmueble.bien_mueble.id %}">{{ donaciones.lote_bienmueble.bien_mueble|title }}</a>
                        {% else %}
                            <i class="material-icons">event_seat</i> {{ donaciones.lote_bienmueble.bien_mueble }}
                        {% endif %}
                    {% elif donaciones.lote_medicamento %}
                        {% if perms.donaciones.change_medicamento %}
                            <i class="material-icons">local_pharmacy</i> <a href="{% url 'consultarLotes' donaciones.lote_medicamento.medicamento.id %}">{{ donaciones.lote_medicamento.medicamento|title }}</a>
                        {% else %}
                            <i class="material-icons">local_pharmacy</i> {{ donaciones.lote_medicamento.medicamento }}
                        {% endif %}
                    {% else %}
                        <i class="material-icons">attach_money</i> Efectivo
                    {% endif %}</td>
                    {% if donaciones.lote_bienmueble %}
                        <td>{{donaciones.monto_inicial}} unidades</td>
                    {% elif donaciones.lote_medicamento %}
                        <td>{{donaciones.monto_inicial}} unidades</td>
                    {% else %}
                        <td>$ {{donaciones.monto_inicial|floatformat:2}}</td>
                    {% endif %}

                    {% if donaciones.lote_bienmueble %}
                        <td>No Aplica</td>
                    {% elif donaciones.lote_medicamento %}
                        <td>No Aplica</td>
                    {% else %}
                        {% if donaciones.fecha_remesa %}
                            <td> Remesado </td>
                        {% else %}
                            <td>Sin Remesar</td>
                        {% endif %}
                    {% endif %}

                    {% if donaciones.comprobante %}
                            <td> Solicitado </td>
                        {% else %}
                            <td>No Solicitado</td>
                        {% endif %}

                    {% if perms.donaciones.change_donacion%}
                        <td>
                            {% if donaciones.lote_bienmueble_id != null %}
                                <a class="btn btn-primary" href="/donaciones/{{donaciones.id}}"><i class="material-icons">edit</i></a>

                            {% elif donaciones.lote_medicamento_id == null and donaciones.lote_bienmueble_id == null %}
                                <a class="btn btn-primary" href="/actualizar_donacion/{{donaciones.id}}"><i class="material-icons">edit</i></a>

                            {% else%}
                                 <a class="btn btn-primary" href="/donaciones_lote/{{donaciones.id}}"><i class="material-icons">edit</i></a>

                            {% endif %}

                        </td>
                    {% endif %}

                </tr>

            {% endfor %}
            </tbody>
        </table>
        {% if messages %}
            {% for mensaje in messages %}
                <script type="text/javascript">
                    (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
                </script>
            {% endfor %}
        {% endif %}

        {% if mensaje %}
            <script type="text/javascript">
                (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
            </script>
        {% endif %}
    </main>

{%endblock%}

donaciones/templates/donaciones/consulta_lote_muebles.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main id="movermain" class="consulta-tabla">
        <header>
            <div class="nav-wrapper">

            </div>
        </header>
        <table class="table table-striped table-bordered table-hover" data-toggle="bootgrid" id = "moverTabla">
            <thead>
            <tr>
                <th>Fecha de Ingreso</th>
                <th>Bien Mueble</th>
                <th>Existencia</th>


                {% if perms.donaciones.change_lotebienmueble%}
                    <th>Modificar</th>
                {% endif %}
            </tr>
            </thead>

            <tbody>
            {% for lote_muebles in lote_muebles_list %}
                <tr>
                    <td>{{lote_muebles.fecha_ingreso}}</td>
                    <td>{{lote_muebles.bien_mueble|title}}</td>
                    <td>{{lote_muebles.existencias}}</td>

                    {% if perms.donaciones.change_lotebienmueble%}
                        <td>
                            <a class="btn btn-primary" href="/actualizar_lote_mueble/{{lote_muebles.id}}"><i class="material-icons">edit</i></a>
                        </td>
                    {% endif %}
                </tr>

            {% endfor %}
            </tbody>
        </table>
        <br>
        <a class="btn btn-primary" href="javascript:history.back()" >Regresar
            <i class="material-icons right">reply</i></a>
        {% if messages %}
            {% for mensaje in messages %}
                <script type="text/javascript">
                    (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
                </script>
            {% endfor %}
        {% endif %}
    </main>

{%endblock%}

donaciones/templates/donaciones/consultar_donadores.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main id="movermain" class="consulta-tabla">
        <header>

        </header>
        <table class="table table-striped table-bordered table-hover" data-toggle="bootgrid" id = "moverTabla">
            <thead>
            <tr>
                <th>Nombres</th>
                <th>Apellidos</th>
                <th>Telefono</th>
                <th>Correo Electronico</th>
                <th>Institucion</th>
                {% if perms.donaciones.delete_donador%}
                    <th>Activo</th>
                {% endif %}

                {% if perms.donaciones.change_donador%}
                    <th>Gestionar</th>
                {% endif %}
            </tr>
            </thead>

            <tbody>
            {% for donador in donadores_list %}
                <tr>
                    <td>{{donador.nombre|title}}</td>
                    <td>{{donador.apellido|title}}</td>
                    <td>{{donador.telefono}}</td>
                    {% if donador.email is not None %}
                        <td>{{donador.email}}</td>
                    {% elif donador.email  is None  %}
                        <td>No Posee</td>
                    {% endif %}
                    {% if donador.institucion is not None %}
                        <td>{{donador.institucion.nombre_institucion|title}}</td>
                    {% elif donador.institucion  is None  %}
                        <td>Donador Indepediente</td>
                    {% endif %}
                    {% if perms.donaciones.delete_donador%}
                        {% if donador.activo %}
                            <td style="text-align:center"><a class="btn btn-primary" href="/confirmar_desactivar/{{donador.id}}"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></a></td>
                        {% elif not donador.activo %}
                            <td><a class="btn btn-danger" href="/confirmar_desactivar/{{donador.id}}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
                        {% endif %}
                    {% endif %}
                    {% if perms.donaciones.change_donador%}
                        <td>
                            <a class="btn btn-primary" href="/actualizar_donadores/{{donador.id}}"><i class="material-icons">edit</i></a>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if messages %}
            {% for mensaje in messages %}
                <script type="text/javascript">
                    (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
                </script>
            {% endfor %}
        {% endif %}

        {% if mensaje %}
            <script type="text/javascript">
                (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
            </script>
        {% endif %}
    </main>

{%endblock%}