SI_MPJ/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('autenticacion.urls')),
    url(r'^', include('administracion.urls')),
    url(r'^', include('control.urls')),
    url(r'^', include('donaciones.urls')),
    url(r'^admin/', admin.site.urls),
]

administracion/urls.py
# -*- coding: utf8 -*-
"""
Nombre del Módulo: Archivo de urls para la app “administracion”
Autores: Francisco Rivas, Kevin Rodríguez, Fernando Rivas, Irving Oliva, Martin Valle
Última fecha de modificación: 04/10/2017
"""
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views
from django.contrib.auth.decorators import permission_required

urlpatterns = [
    #url(r'^$', views.index, name='index'),
    # Inician urls para pacientes
    url(r'^pacientes/$', views.consultarPacientes, name='consultarPacientes'),
    url(r'^confirmar_desactivar_paciente/(?P<paciente_id>[0-9]+)$', views.confirmar_desactivar_paciente, name='confirmar_desactivar_paciente'),
    url(r'^desactivar_paciente/(?P<paciente_id>[0-9]+)$', views.desactivar_paciente, name='desactivar_paciente'),
    url(r'^actualizar_paciente/(?P<pk>\d+)$', views.PacienteUpdate.as_view(),name='PacienteUpdate'),
    url(r'^agregar_paciente/', views.registroPaciente, name='registrar_paciente'),
    url(r'^actualizar_responsable/(?P<paciente_id>[0-9]+)$', views.actualizar_responsable, name='actualizar_responsable'),
    # Finalizan urls para pacientes

    # Inician urls para empleados
    url(r'^empleados/$', views.consultarEmpleados, name='consultarEmpleados'),
    url(r'^confirmar_desactivar_empleado/(?P<empleado_id>[0-9]+)$', views.confirmar_desactivar_empleado, name='confirmar_desactivar_empleado'),
    url(r'^desactivar_empleado/(?P<empleado_id>[0-9]+)$', views.desactivar_empleado, name='desactivar_empleado'),
    url(r'^actualizar_empleado/(?P<pk>\d+)$', views.EmpleadoUpdate.as_view(),name='EmpleadoUpdate'),
    url(r'^agregar_empleado/', views.registroEmpledo.as_view(), name='registrar_empleado'),
    # Finalizan urls para empleados

    # Inician urls para usuarios
    url(r'^agregar_usuario/', views.registroUsuario, name='registrar_usuario'),
    # Finalizan urls para usuarios

    # Inician urls para servicios
    url(r'^agregar_servicio/$', views.AgregarServicio.as_view(), name='agregar_servicio'),
    url(r'^servicios/$', views.consultarServicio, name='consultarServicio'),
    url(r'^actualizar_servicio/(?P<pk>\d+)$', views.ModificarServicio.as_view(),name='ServicioUpdate'),
    # Finalizan urls para servicios

    # Inician urls para tarifas
    url(r'^agregar_tarifa1/$', views.AgregarTarifa1.as_view(), name='agregar_tarifa1'),
    url(r'^agregar_tarifa2/$', views.AgregarTarifa2.as_view(), name='agregar_tarifa2'),
    url(r'^tarifas1/$', views.consultarTarifa1, name='consultarTarifa1'),
    url(r'^actualizar_tarifa1/(?P<pk>\d+)$', views.ModificarTarifa1.as_view(),name='Tarifa1Update'),
    url(r'^tarifas2/$', views.consultarTarifa2, name='consultarTarifa2'),
    url(r'^actualizar_tarifa2/(?P<pk>\d+)$', views.ModificarTarifa2.as_view(),name='Tarifa2Update'),
    # Finalizan urls para tarifas

    # Inician urls para Estudio Socio-Economico
    url(r'^agregar_estudio/(?P<id>[0-9]+)$', views.registroEstudio, name='registro_socio'),
    url(r'^actualizar_estudio/(?P<pk>\d+)$', views.ModificarEstudio.as_view(),name='EstudioUpdate'),
    # Finalizan urls para Estudio Socio-Economico

    # Inician urls para especialidades
    url(r'^agregar_especialidad/$', views.AgregarEspecialidad.as_view(), name='agregar_especialidad'),
    url(r'^especialidad/$', views.consultarEspecialidad, name='consultarEspecialidad'),
    url(r'^actualizar_especialidad/(?P<pk>\d+)$', views.ModificarEspecialidad.as_view(),name='EspecialidadUpdate'),
    url(r'^confirmar_desactivar_especialidad/(?P<especialidad_id>[0-9]+)$', views.confirmar_desactivar_especialidad, name='confirmar_desactivar_especialidad'),
    url(r'^desactivar_especialidad/(?P<especialidad_id>[0-9]+)$', views.desactivar_especialidad, name='desactivar_especialidad'),
    # Finalizan urls para especialidades

    # Inician Urls para Expediente Medico
    url(r'^expediente/(?P<pk>\d+)/$', views.expediente, name='expediente'),
    url(r'^expediente/pre_diagnostico/(?P<pk>\d+)/$', views.PreDiagnostico.as_view(), name='pre_diagnostico'),
    # Finalizan urls para Expediente Medico

    # Inician Urls para Grupos de Apoyo
    url(r'^grupos_apoyo/participantes/(?P<grupo_apoyo_id>\d+)/$', views.asistencia_participantes, name='asistencia_participantes'),
    url(r'^agregar_grupo/$', views.AgregarGrupo.as_view(), name='agregar_grupo'),
    url(r'^grupos_apoyo/(?P<pk>\d+)$', views.ModificarGrupo.as_view(),name='GrupoApoyoUpdate'),
    url(r'^grupos_apoyo/$', views.consultarGrupo, name='consultarGrupos'),
    url(r'^agregar_participante/$', views.AgregarParticipante.as_view(), name='agregar_participante'),
    url(r'^participantes/(?P<pk>\d+)$', views.ModificarParticipante.as_view(),name='ParticipanteUpdate'),
    url(r'^participantes/$', views.consultarParticipantes, name='consultarParticipantes'),
    url(r'^confirmar_desactivar_participante/(?P<participante_id>[0-9]+)$', views.confirmar_desactivar_participante, name='confirmar_desactivar_participante'),
    url(r'^desactivar_participante/(?P<participante_id>[0-9]+)$', views.desactivar_participante, name='desactivar_participante'),
    # Finalizan Urls para Grupos de Apoyo

    # Inicio de las URL'S para la generacion de los pdf
    url(r'^reportes/$', views.reportes, name='reportes'),
    url(r'^reportes/consultas_medicos$', views.consultas_medicos, name='consultas_medicos'),
    url(r'^reportes/consultas_especialidades$', views.consultas_especialidades, name='consultas_especialidades'),
    url(r'^reportes/examenes_realizados$', views.examenes_realizados, name='examenes_realizados'),
    url(r'^reportes/reporte_medicamentos$', views.reporte_inventario, name='reporte_medicamentos'),
    url(r'^reportes/donaciones/$', views.donaciones, name='donaciones'),
    url(r'^reportes/listado_donadores$', views.lista_donadores, name='listadoDonadores'),
    # url(r'^reportes/examenes$', views.ReporteExamenesPDFView.as_view(), name='reportesEx'),
    # url(r'^reportes/especialidades/$', views.ReporteEspecialidadesPDFView.as_view(), name='reporteEsp'),

    url(r'^agregar_ponente/$', views.AgregarPonente.as_view(), name='agregar_ponente'),
    url(r'^ponentes/$', views.consultarPonentes, name='consultarPonentes'),
    url(r'^ponentes/(?P<pk>\d+)$', views.ModificarPonente.as_view(),name='PonenteUpdate'),
    url(r'^confirmar_desactivar_ponente/(?P<ponente_id>[0-9]+)$', views.confirmar_desactivar_ponente, name='confirmar_desactivar_ponente'),
    url(r'^desactivar_ponente/(?P<ponente_id>[0-9]+)$', views.desactivar_ponente, name='desactivar_ponente'),
]

administracion/models.py
# -*- coding: utf-8 -*-
"""
Nombre del Módulo: Archivo de modelos para la app “administracion”
Autores: Francisco Rivas, Kevin Rodríguez, Fernando Rivas, Irving Oliva
Última fecha de modificación: 04/10/2017
"""
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.core.validators import MinValueValidator

# Create your models here.

SEXO_CHOICES = (
    ('M', 'Masculino'),
    ('F', 'Femenino'),
)

GRUPO_CHOICES = (('1', 'Programado'),('2', 'Finalizado'))

class Departamento(models.Model):
    nombre = models.CharField(max_length=32, blank=False, null=False)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name='Departamento'
        verbose_name_plural = 'Departamentos'


class Municipio(models.Model):
    nombre = models.CharField(max_length=64, blank=False, null=False)
    departamento = models.ForeignKey(Departamento, blank=False, null=False)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Municipio'
        verbose_name_plural = 'Municipios'

class EstadoCivil(models.Model):
    nombre = models.CharField(max_length = 30,unique=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name='Estado Civil'
        verbose_name_plural = 'Estados Civiles'

class Especialidad(models.Model):
    nombre = models.CharField('Nombre de la Especialidad', max_length=30, unique=True, blank=False, null=False)
    activo = models.BooleanField('¿Disponible?', default=True)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ["nombre"]
        verbose_name = 'Especialidad'
        verbose_name_plural = 'Especialidades'


class Empleado(models.Model):
    nombre = models.CharField('Nombres del empleado', max_length = 40)
    apellido = models.CharField('Apellidos del empleado', max_length = 40)
    dui = models.CharField('Número de DUI', max_length = 10, help_text='Formato: XXXXXXXX-X',unique=True)
    nit = models.CharField('Número de NIT', max_length = 17, help_text='Formato: XXXX-XXXXXX-XXX-X',unique=True)
    sexo = models.CharField('Sexo', max_length = 1, choices=SEXO_CHOICES, blank=False, null=False)
    fecha_nacimiento=models.DateField('Fecha de nacimiento', help_text='Formato: DD/MM/AAAA')
    estado_civil = models.ForeignKey(EstadoCivil, null = False)
    telefono = models.CharField('Número de teléfono', max_length = 9, help_text='Formato: XXXX-XXXX',unique=True)
    direccion = models.CharField('Dirección', max_length = 256, help_text='Dirección de su residencia')
    activo = models.BooleanField('¿Activo?', default = True)
    user = models.OneToOneField(User, null = True, help_text='Usuario relacionado')
    especialidad = models.ForeignKey(Especialidad, null=True, blank=True)


    def __str__(self):
        return '{} {}'.format(self.nombre.title(), self.apellido.title())

    class Meta:
        ordering = ['apellido']
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'

class Paciente(models.Model):
    nombre = models.CharField('Nombres del paciente', max_length = 40,blank=False,null=False)
    apellido = models.CharField('Apellidos del paciente', max_length = 40,blank=False,null=False)
    dui = models.CharField('Número de DUI', max_length = 10, blank=True, null=True, help_text='Formato: XXXXXXXX-X',unique=True)
    nit = models.CharField('Número de NIT', max_length = 17, blank=True, null=True, help_text='Formato: XXXX-XXXXXX-XXX-X',unique=True)
    sexo = models.CharField('Sexo', max_length = 1, choices=SEXO_CHOICES,blank=False,null=False)
    fecha_nacimiento = models.DateField('Fecha de nacimiento', help_text='Formato: DD/MM/AAAA',blank=False,null=False)
    telefono = models.CharField('Número de teléfono', max_length = 9, help_text='Formato: XXXX-XXXX',blank=False,null=False, unique=False)
    departamento = models.ForeignKey(Departamento, blank=False, null=False)
    municipio = models.ForeignKey(Municipio, blank=False, null=False)
    direccion = models.CharField('Dirección', max_length = 256, help_text='Dirección de su residencia',blank=False,null=False)
    estado_civil = models.ForeignKey(EstadoCivil, null = False,blank=False)
    email = models.EmailField('Correo Electrónico', max_length=254, blank=True, null=True, unique=True)
    activo = models.BooleanField('¿Activo?', default = True)

    def get_absolute_url(self):
        # return reverse('consultarPacientes')
        return reverse('listar', kwargs={"num_expediente": self.expediente})

    def __str__(self):
        return '{} - {} {}'.format(self.expediente.num_expediente, self.nombre.title(), self.apellido.title())

    class Meta:
        ordering = ['expediente']
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'


class Expediente(models.Model):
    num_expediente = models.CharField('Número de expediente', max_length = 5,unique=True)
    paciente = models.OneToOneField(Paciente, null = False, help_text='Expediente asignado')
    fecha_apertura = models.DateField('Fecha de apertura', auto_now_add=True)
    diagnostico = models.BooleanField('Diagnóstico', default=False, help_text='¿Presenta diagnóstico?')
    tratamiento = models.BooleanField('Tratamiento', default=False, help_text='¿Ya esta en tratamiento?')
    lugar = models.CharField('Lugar de atención', max_length=80, blank=True, null=True)
    creado_por = models.ForeignKey(Empleado, null = False)


    def __str__(self):
        return self.num_expediente

    class Meta:
        ordering = ["num_expediente"]
        verbose_name = 'Expediente'
        verbose_name_plural = 'Expedientes'


class Responsable(models.Model):
    nombre = models.CharField('Nombres del responsable', max_length = 40)
    apellido = models.CharField('Apellidos del responsable', max_length = 40)
    parentesco = models.CharField('Parentesco', max_length = 10)
    telefono = models.CharField('Número de teléfono', max_length=9, help_text='Formato: XXXX-XXXX', blank=False, null=True, unique=False)
    paciente = models.ForeignKey(Paciente, null = False, blank=False, help_text='Responsable de')


    def __str__(self):
        return '{} {}'.format(self.nombre, self.apellido)

    class Meta:
        ordering = ['apellido']
        verbose_name = 'Responsable'
        verbose_name_plural = 'Responsables'

class Servicio(models.Model):
    nombre = models.CharField('Nombre del Servicio', max_length=30, unique=True, blank=False, null=False)
    tipo = models.CharField('Tipo de Servicio', max_length=1, choices=(('1', 'Básico'),('2', 'Médico')), blank=False, null=False)
    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ["tipo"]
        verbose_name = 'Servicio'
        verbose_name_plural = 'Servicios'

class Tarifa(models.Model):
    nombre = models.CharField('Descripción', max_length=255, blank=False, null=False, unique=True)
    monto=models.DecimalField('Monto', max_digits=5, decimal_places=2, blank=False, null=False, validators = [MinValueValidator(0)])
    tarifa_padre = models.ForeignKey('self', null=True, blank=True)
    examen = models.ForeignKey('control.Examen', null=True, blank=True)

    def __str__(self):
        return self.nombre

    class Meta:
        unique_together = ('tarifa_padre', 'examen',)
        verbose_name = 'Tarifa'
        verbose_name_plural = 'Tarifas'


class Socioeconomico(models.Model):
    vivienda = models.BooleanField('Vivienda', default=False, blank=False, null=False)
    vehiculo = models.BooleanField('Vehiculo', default=False, blank=False, null=False)
    trabaja = models.BooleanField('Trabaja', default=False, blank=False, null=False)
    esp_trabajo = models.CharField('Especifique Trabajo', max_length = 300,  blank=True, null=True)
    estudia = models.BooleanField('Estudia', default=False, blank=False, null=False)
    negocio = models.BooleanField('Negocio', default=False, blank=False, null=False)
    pensionado = models.BooleanField('Pensionado', default=False, blank=False, null=False)
    tarifa = models.ForeignKey(Tarifa, null=False, blank=False, help_text='Tarifa asignada')
    expediente = models.OneToOneField(Expediente, help_text='Numero de Expediente relacionado')
    servicios = models.ManyToManyField(Servicio, blank=True)

    def __str__(self):
        return self.expediente.num_expediente


    class Meta:
        ordering = ["expediente"]
        verbose_name = 'Estudio Socioeconómico'
        verbose_name_plural = 'Estudios Socioeconómicos'

class Participante(models.Model):
    nombre = models.CharField('Nombres del participante', max_length=40, blank=False, null=False)
    apellido = models.CharField('Apellidos del participante', max_length=40, blank=False, null=False)
    telefono = models.CharField('Número de teléfono', max_length=9, help_text='Formato: XXXX-XXXX', blank=False, null=False, unique=False)
    departamento = models.ForeignKey(Departamento, blank=False, null=False)
    municipio = models.ForeignKey(Municipio, blank=False, null=False)
    direccion = models.CharField('Dirección', max_length=256, help_text='Dirección de su residencia', blank=False, null=False)
    email = models.EmailField('Correo Electrónico', max_length=254, blank=True, null=True, unique=True)
    activo = models.BooleanField('¿Activo?', default=True)

    def __str__(self):
        return '{} {}'.format(self.nombre, self.apellido)


    class Meta:
        ordering = ["nombre"]

class Ponente(models.Model):
    nombre = models.CharField('Nombres del Ponente', max_length=40, blank=False, null=False)
    apellido = models.CharField('Apellidos del Ponente', max_length=40, blank=False, null=False)
    telefono = models.CharField('Número de teléfono Fijo', max_length=9, help_text='Formato: XXXX-XXXX', blank=True, null=True)
    telefono_cel = models.CharField('Número de teléfono Celular', max_length=9, help_text='Formato: XXXX-XXXX', blank=False, null=False, unique=False)

administracion/templates/administracion/consultaPacientes.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main id="movermain" class="consulta-tabla">

        <table class="table table-striped table-bordered table-hover" data-toggle="bootgrid" id = "moverTabla">
            <thead>
            <tr>
                <th>No. Expediente</th>
                <th>Nombres</th>
                <th>Apellidos</th>
                <th>Telefono</th>
                <th>Direccion</th>
                {% if perms.administracion.delete_paciente%}
                    <th>Activo</th>
                {% endif %}
                {% if perms.administracion.change_paciente%}
                    <th>Modificar</th>
                {% endif %}
                {% if perms.administracion.change_responsable%}
                    <th>Responsable</th>
                {% endif %}
            </tr>
            </thead>

            <tbody>
            {% for pacientes in pacientes_list %}
                <tr>
                    <td><a href="/expediente/{{ pacientes.expediente.id }}">{{pacientes.expediente}}</a></td>
                    <td>{{pacientes.nombre|title}}</td>
                    <td>{{pacientes.apellido|title}}</td>
                    <td>{{pacientes.telefono}}</td>
                    <td>{{pacientes.direccion}}</td>
                    {% if perms.administracion.delete_paciente%}
                        {% if pacientes.activo %}
                            <td style="text-align:center"><a class="btn btn-primary" href="/confirmar_desactivar_paciente/{{pacientes.id}}"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></a></td>
                        {% elif not pacientes.activo %}
                            <td><a class="btn btn-danger" href="/confirmar_desactivar_paciente/{{pacientes.id}}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
                        {% endif %}
                    {% endif %}
                    {% if perms.administracion.change_paciente%}
                        <td>
                            <a class="btn btn-primary" href="/actualizar_paciente/{{pacientes.id}}"><i class="material-icons">edit</i></a>
                        </td>
                    {% endif %}
                    {% if perms.administracion.change_responsable%}
                        <td>
                            <a class="btn btn-primary" href="/actualizar_responsable/{{pacientes.id}}"><i class="material-icons">edit</i></a>
                        </td>
                    {% endif %}
                </tr>

            {% endfor %}
            </tbody>
        </table>
        {% if messages %}
            {% for mensaje in messages %}
                <script type="text/javascript">
                    (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
                </script>
            {% endfor %}
        {% endif %}

        {% if mensaje %}
            <script type="text/javascript">
                (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
            </script>
        {% endif %}
    </main>

{%endblock%}

administracion/templates/administracion/consultar_especialidad.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main id="movermain" class="consulta-tabla">
        <table class="table table-striped table-bordered table-hover" data-toggle="bootgrid" id = "moverTabla">
            <thead>
            <tr>
                <th>Descripcion de Especialidades</th>
                {% if perms.administracion.delete_especialidad%}
                    <th>¿Disponible?</th>
                {% endif %}
                {% if perms.administracion.change_especialidad%}
                    <th>Gestionar</th>
                {% endif %}
            </tr>
            </thead>

            <tbody>
            {% for especialidad in especialidad_list %}
                <tr>
                    <td>{{especialidad.nombre|title}}</td>

                    {% if perms.administracion.delete_especialidad%}
                        {% if especialidad.activo %}
                            <td style="text-align:center"><a class="btn btn-primary" href="/confirmar_desactivar_especialidad/{{especialidad.id}}"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></a></td>
                        {% elif not especialidad.activo %}
                            <td><a class="btn btn-danger" href="/confirmar_desactivar_especialidad/{{especialidad.id}}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
                        {% endif %}
                    {% endif %}

                    {% if perms.administracion.change_especialidad%}
                        <td>
                            <a class="btn btn-primary" href="/actualizar_especialidad/{{especialidad.id}}"><i class="material-icons">edit</i></a>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if messages %}
            {% for mensaje in messages %}
                <script type="text/javascript">
                    (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
                </script>
            {% endfor %}
        {% endif %}
    </main>

{%endblock%}

administracion/templates/administracion/consultar_participantes.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main id="movermain" class="consulta-tabla">
        <header>

        </header>
        <table class="table table-striped table-bordered table-hover" data-toggle="bootgrid" id = "moverTabla">
            <thead>
            <tr>

                <th>Nombres</th>
                <th>Apellidos</th>
                <th>Direccion</th>
                <th>Telefono</th>
                <th>Correo Electronico</th>

                {% if perms.administracion.delete_participante%}
                    <th>Activo</th>
                {% endif %}

                {% if perms.administracion.change_participante%}
                    <th>Gestionar</th>
                {% endif %}
            </tr>
            </thead>

            <tbody>
            {% for participante in participantes_list %}
                <tr>
                    <td>{{participante.nombre|title}}</td>

                    <td>{{participante.apellido|title}}</td>
                    <td>{{participante.direccion}}</td>
                    <td>{{participante.telefono}}</td>
                    {% if participante.email is not None %}
                        <td>{{participante.email}}</td>
                    {% else %}
                        <td>No posee</td>
                    {% endif %}
                    {% if perms.administracion.delete_participante%}
                        {% if participante.activo %}
                            <td style="text-align:center"><a class="btn btn-primary" href="/confirmar_desactivar_participante/{{participante.id}}"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></a></td>
                        {% elif not participante.activo %}
                            <td><a class="btn btn-danger" href="/confirmar_desactivar_participante/{{participante.id}}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
                        {% endif %}
                    {% endif %}

                    {% if perms.administracion.change_participante%}
                        <td>
                            <a class="btn btn-primary" href="/participantes/{{participante.id}}"><i class="material-icons">edit</i></a>

                        </td>
                    {% endif %}
                </tr>

            {% endfor %}
            </tbody>
        </table>
        {% if messages %}
            {% for mensaje in messages %}
                <script type="text/javascript">
                    (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
                </script>
            {% endfor %}
        {% endif %}
    </main>

{%endblock%}

administracion/templates/administracion/consultar_ponentes.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main id="movermain" class="consulta-tabla">
        <header>

        </header>
        <table class="table table-striped table-bordered table-hover" data-toggle="bootgrid" id = "moverTabla">
            <thead>
            <tr>

                <th>Nombres</th>
                <th>Apellidos</th>
                <th>Telefono Celular</th>
                <th>Telefono Fijo</th>
                <th>Correo Electronico</th>
                <th>Profesión</th>

                {% if perms.administracion.delete_ponente%}
                    <th>Activo</th>
                {% endif %}

                {% if perms.administracion.change_ponente%}
                    <th>Gestionar</th>
                {% endif %}
            </tr>
            </thead>

            <tbody>
            {% for ponente in ponentes_list %}
                <tr>
                    <td>{{ponente.nombre|title}}</td>

                    <td>{{ponente.apellido|title}}</td>
                    <td>{{ponente.telefono_cel}}</td>
                    <td>{{ponente.telefono}}</td>
                    {% if ponente.email is not None %}
                        <td>{{ponente.email}}</td>
                    {% else %}
                        <td>No posee</td>
                    {% endif %}
                    <td>{{ponente.profesion}}</td>
                    {% if perms.administracion.delete_ponente%}
                        {% if ponente.activo %}
                            <td style="text-align:center"><a class="btn btn-primary" href="/confirmar_desactivar_ponente/{{ponente.id}}"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></a></td>
                        {% elif not ponente.activo %}
                            <td><a class="btn btn-danger" href="/confirmar_desactivar_ponente/{{ponente.id}}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
                        {% endif %}
                    {% endif %}

                    {% if perms.administracion.change_ponente%}
                        <td>
                            <a class="btn btn-primary" href="/ponentes/{{ponente.id}}"><i class="material-icons">edit</i></a>

                        </td>
                    {% endif %}
                </tr>

            {% endfor %}
            </tbody>
        </table>
        {% if messages %}
            {% for mensaje in messages %}
                <script type="text/javascript">
                    (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
                </script>
            {% endfor %}
        {% endif %}
    </main>

{%endblock%}

administracion/templates/administracion/consultar_servicio.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main id="movermain" class="consulta-tabla">
        <header>

        </header>
        <table class="table table-striped table-bordered table-hover" data-toggle="bootgrid" id = "moverTabla">
            <thead>
            <tr>
                <th>Nombre</th>
                <th>Tipo</th>
                {% if perms.administracion.change_servicio%}
                    <th>Gestionar</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for servicios in servicios_list %}
                <tr>
                    <td>{{servicios.nombre|title}}</td>
                    {% if servicios.tipo == '1' %}
                        <td>Basico</td>
                    {% else %}
                        <td>Medico</td>
                    {% endif %}
                    {% if perms.administracion.change_servicio%}
                        <td>
                            <a class="btn btn-primary" href="/actualizar_servicio/{{servicios.id}}"><i class="material-icons">edit</i></a>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if messages %}
            {% for mensaje in messages %}
                <script type="text/javascript">
                    (function () { Materialize.toast('{{ mensaje }}', 4000, 'rounded') })();
                </script>
            {% endfor %}
        {% endif %}
    </main>

{%endblock%}